/* eslint-disable react/prop-types */
import Head from 'next/head';
import React, { useState } from 'react';
import BreadCrumb from '../BreadCrumb/BreadCrumb';
import CategoriesContext from '../context/CategoriesContext';
import Navbar from '../Navbar/Navbar';
import styles from './Layout.module.scss';

export default function Layout({ children }) {
  const [categories, setCategories] = useState([]);
  const contextValues = { categories, setCategories };
  return (
    <>
      <Head>
        <title>Meli Frontend Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo_ML@2x.png.png" />
      </Head>
      <div className={`grid-container ${styles.container}`}>
        <Navbar />
        <CategoriesContext.Provider
          value={contextValues}
        >
          <BreadCrumb
            categories={categories}
          />
          {children}
        </CategoriesContext.Provider>
      </div>
    </>
  );
}
