/* eslint-disable react/prop-types */
import Head from 'next/head';
import NextNProgress from 'nextjs-progressbar';
import React, { useState } from 'react';
import CategoriesContext from '../../context/CategoriesContext';
import BreadCrumb from '../BreadCrumb/BreadCrumb';
import Navbar from '../Navbar/Navbar';
import styles from './Layout.module.scss';
/**
 * Layout of the page including the navbar and the breadcrumbs
 * @param props - props object of react component
 * @param props.children - children to render inside the layout
 */
export default function Layout({ children }) {
  const [categories, setCategories] = useState([]);
  const contextValues = { categories, setCategories };
  return (
    <>
      <NextNProgress height={4} />
      <Head>
        <title>Meli Frontend Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo_ML@2x.png.png" />
      </Head>
      <div className={`grid-container ${styles.container}`}>
        <Navbar />
        <CategoriesContext.Provider
          value={contextValues}
        >
          <BreadCrumb
            categories={categories}
          />
          {children}
        </CategoriesContext.Provider>
      </div>
    </>
  );
}
