import Head from 'next/head'
import React, {Fragment} from 'react'
import Navbar from '../Navbar/Navbar'
import styles from './Layout.module.scss'


export default function Layout({children}) {
    return (
        <Fragment>
            <Head>
                <title>Meli Frontend Test</title>
                 <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`grid-container ${styles.container}`}>
                <Navbar/>
                {children}
            </div>
        </Fragment>
    )
}
